WITH
    fonte_funcionarios AS (
        SELECT *
        FROM {{ source('erp_northwind', 'EMPLOYEE') }}
        
)

, renovacao AS (
    SELECT   
        CAST(ID AS INT) AS PK_FUNCIONARIO
     ,  CAST(REPORTSTO AS INT) AS FK_GERENTE
     ,  FIRSTNAME ||' '|| LASTNAME AS NOME_FUNCIONARIO
     ,  CAST(TITLE AS VARCHAR) AS CARGO_FUNCIONARIO
     ,  CAST(BIRTHDATE AS DATE) AS DT_NASCIMENTO_FUNCIONARIO
     ,  CAST(HIREDATE AS DATE) AS DT_CONTRATACAO
     ,  CAST(CITY AS VARCHAR) AS CIDADE_FUNCIONARIO
     ,  CAST(REGION AS VARCHAR) AS REGIAO_FUNCIONARIO
     ,  CAST(COUNTRY AS VARCHAR) AS PAIS_FUNCIONARIO
     --,  CAST(TITLEOFCOURTESY AS VARCHAR) AS
     --,  CAST(ADDRESS AS VARCHAR) AS 
     --,  CAST(POSTALCODE AS VARCHAR) AS
     --,  CAST(HOMEPHONE AS VARCHAR) AS
     --,  CAST(EXTENSION AS VARCHAR) AS
     --,  CAST(PHOTO AS VARCHAR) AS
     --,  CAST(NOTES AS VARCHAR) 
     --,  CAST(PHOTOPATH AS VARCHAR) AS
    FROM fonte_funcionarios

)

SELECT *
FROM renovacao
